/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';

// Precache files generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Event listener for service worker installation
self.addEventListener('install', (event) => {
  self.skipWaiting();
});

// Event listener for service worker activation
self.addEventListener('activate', (event) => {
  self.clients.claim();
});
